#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Context environment

# Symfony
SYMFONY_ENV=prod
SYMFONY_DEBUG=0
